[package]
name = "svc16"
version = "0.2.0"
edition = "2021"
authors = ["Jan Neuendorf"]
description = "An emulator for a simple virtual computer"
license="MIT"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
minifb = "0.27.0"
thiserror = "2.0.3"
